# Generated by Django 2.0 on 2019-05-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_short',
            name='code',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='url_short',
            name='long_url',
            field=models.CharField(max_length=2000, unique=True),
        ),
    ]
